.\"
.\" $Id: milter-greylist.8,v 1.21 2004/03/30 08:00:25 manu Exp $
.\"
.\" Copyright (c) 2004 Emmanuel Dreyfus
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"        This product includes software developed by Emmanuel Dreyfus
.\"
.\" THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
.\" DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
.\" (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
.\" SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
.\" STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
.\" OF THE POSSIBILITY OF SUCH DAMAGE.
.\"

.Dd Feb 21, 2004
.Dt milter-greylist 8
.Os
.Sh NAME
.Nm milter-greylist
.Nd grey listing filter for sendmail
.Sh SYNOPSIS
.Nm
.Op Fl A
.Op Fl a Ar delay
.Op Fl D
.Op Fl d Ar dumpfile
.Op Fl f Ar configfile
.Op Fl q
.Op Fl r
.Op Fl T
.Op Fl u Ar username
.Op Fl v
.Op Fl w Ar delay
.Op Fl L cidrmask
.Op Fl P pidfile
.Fl p Ar socket
.Sh DESCRIPTION
.Nm 
is a mail filter for sendmail that implements grey listing,
a spam filtering technique proposed by Evan Harris.
.Pp
Grey listing works by assuming that contrarily to legitimate MTA, spam engines
will not retry sending their junk mail on a temporary error. The filter
will always temporarily reject mail on a first attempt, and 
accept it after some time has elapsed.
.Pp
If spammers ever try to resend rejected messages, we can assume they will 
not stay idle between the two sends. Odds are good that the spammer will 
send a mail to an honey pot address and get blacklisted in a distributed 
black list before the second attempt.
.Pp
Of course, the filter can be configured to not apply grey listing to some
hosts or networks. You can whitelist friendly SMTP servers, and you should
whitelist your own network, otherwise your SMTP clients will have real trouble to 
send e-mail. Whitelisting localhost is also a must.
.Pp
.Nm
works with two files. 
.Pa greylist.conf
is the configuration file. It holds the whitelist of addresses that will 
not suffer grey list filtering.  It is read once upon 
.Nm
startup, then it will be automatically reloaded whenever a new message
gets in and if it had been modified. You should not send
.Nm
a 
.Li kill -1
as it will just terminate it (libmilter works that way).
.Pp
The format of the file is rather simple: each line gives a network address
block or an e-mail address that is excluded from grey list filtering. 
Here is an example:
.Dl addr 127.0.0.0/8
.Dl addr 192.168.3.0/24
.Dl rcpt John.Doe@example.net
.Pp
The second file is
.Pa greylist.db .
.Nm
will regularly dump its grey list database into this file, which is used
on startup to restore the previous grey list state. If the file does not
exist or is unreadable, 
.Nm
will start with an empty grey list. 
.Pp
The following options are available:
.Bl -tag -width flag
.It Fl A
Normally, 
.Nm
does not greylist senders that succeeded SMTP AUTH. This option disable that
feature and cause authentication to be ignored.
.It Fl a Ar delay
Configure auto-whitelisting. After a tuple (sender IP, sender e-mail, 
recipient e-mail) has been accepted, other identical tuples will get
accepted for 
.Ar delay .
The default is one day. Use zero to disable auto-whitelisting.
A suffix can be added to specify seconds (s), minutes (m), hours (h), 
days (d) or weeks (w). Whithout suffix, values are treated as seconds.
.It Fl D
Do not fork and run in the foreground. Without this flag, 
.Nm
will become a daemon.
.It Fl d Ar dumpfile
Location of the dump file. Default is 
.Pa /var/milter-greylist/greylist.db
.It Fl f Ar configfile
Location of the config file. Default is
.Pa /etc/mail/greylist.conf .
.It Fl L Ar cidrmask
Use 
.Ar cidrmask
as a matching mask when checking IPv4 addresses entries in the greylist. This
is aimed as a workaround to mail farms that re-emit messages from different
IP addresses. With -L 24,
the matching mask is 255.255.255.0, and all addresses within the same class C
network are considered the same. Default is -L 32, 
which corresponds to all addresses considered different.
.It Fl P Ar pidfile
write the daemon's PID to 
.Ar pidfile .
.It Fl p Ar socket
Use 
.Ar socket
as the socket used by 
.Xr sendmail 8
to talk with
.Nm .
This option is mandatory.
.It Fl q
Quiet mode. 
.Nm
will not tell SMTP clients how many time they have to wait before the
message is accepted.
.It Fl r
Display 
.Nm
version and build environnement, then exit.
.It Fl T
Enable test mode. This alters the meaning of recipient lines in 
.Pa greylist.conf ,
so that only messages sent to recipient adresses listed there are 
selected for grey listing.
.It Fl u Ar username
Drop root privileges and switch to 
.Ar username
credentials'. Make sure this user has write access to 
.Pa greylist.db .
.It Fl v
Enable debug output. 
.Nm 
will send messages (and debug output if it is given the
.Fl v
flag) to 
.Xr syslogd 8
with facility LOG_MAIL.
.It Fl w Ar delay
sets the minimum delay between the first attempt and the time
the message can be accepted. Default is 30 minutes. 
A suffix can be added to specify seconds (s), minutes (m), hours (h), 
days (d) or weeks (w). Whithout suffix, values are treated as seconds.
.El
.Sh GREYLIST MX SYNC
.Nm
is now able to sync the greylist between multiple MX. In order to enable
this feature, you need to list the peer MX's in 
.Pa greylist.conf ,
just like this:
.Dl peer 192.0.2.17
.Dl peer 192.0.2.18
.Pp
When peers are configured, 
.Nm
will listen on port defined for the mxglsync service in
.Pa /etc/services 
(defaults to 5252), and it will connect to peers at this port. Each time 
an entry will be added or deleted on one MX, it will be propagated to 
the others. 
.Pp
The protocol is quite simple, just
telnet to your MX at port 5252, and type help to see how it works. Note that
connections will only be accepted from peer MX's, even localhost will be
rejected (and don't ever add localhost as a peer for MX sync, as you will 
cause each entry in the greylist to be added twice).
.Pp
If an MX is down, changes to the greylist will be queued until it gets
back up again. The queue length is limited (default is 1024 entries), and
if it overflows, newer entries will be discarded.
.Sh AUTHOR
.An Emmanuel Dreyfus Aq manu@netbsd.org
.Pp
Thanks to 
.An Helmut Messerer
and
.An Thomas Pfau
for their feebacks on this software.
.Sh SEE ALSO
.Xr sendmail 8 , 
.Xr syslogd 8 .
.Pp
Evan Harris's paper
.Pa http://projects.puremagic.com/greylisting
